In [41]:
import numpy as np

In [42]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye((3), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
np.random.random()

0.623249723684152

In [48]:
np.random.random((2, 3))

array([[0.67574142, 0.44720042, 0.49735392],
       [0.93190445, 0.6054197 , 0.94226644]])

In [49]:
np.random.randn(2, 3)

array([[ 0.81878463,  0.25524113,  0.49320598],
       [ 0.6787406 ,  1.28003707, -0.63374278]])

In [50]:
R = np.random.randn(1000)

In [51]:
R.mean()

0.03733449507284316

In [52]:
np.mean(R)

0.03733449507284316

In [53]:
R.var()  #variance

1.058780963418835

In [54]:
R.std() #standard deviation

1.028970827292414

In [55]:
R = np.random.randn(10000, 3)

In [56]:
np.mean(R, axis=0)

array([0.01225707, 0.00406695, 0.00152189])

In [57]:
R.mean(axis=0)  #previous one and this one both can be used

array([0.01225707, 0.00406695, 0.00152189])

In [58]:
R.mean(axis=1)

array([-0.71208159,  0.58434029,  0.73707121, ...,  0.21279788,
       -0.2244024 ,  0.83596494])

In [59]:
R.mean(axis=1).shape

(10000,)

In [61]:
np.random.randint(0, 10, size = (3, 3))

array([[1, 6, 2],
       [8, 7, 8],
       [5, 6, 1]])