In [2]:
import numpy as np

In [3]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [4]:
L[0]

[1, 2]

In [5]:
L[0][1]

2

In [6]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [7]:
A[0][1]

2

In [8]:
A[0, 1]

2

In [9]:
A[:, 0]

array([1, 3])

In [10]:
A[1,:] #colon notation, select every dimention of the given dimention

array([3, 4])

In [11]:
A.T #transpose of the matrix

array([[1, 3],
       [2, 4]])

In [12]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [13]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [14]:
B = np.array([[1, 2, 3], [4, 5, 6],])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [16]:
A@B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [17]:
np.linalg.det(A)  #determinant of matrix

-2.0000000000000004

In [18]:
np.linalg.inv(A) #inverse of a matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [20]:
np.trace(A)

5

In [21]:
np.diag(A)

array([1, 4])

In [22]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [28]:
lam, V = np.linalg.eig(A)

In [29]:
lam

array([-0.37228132,  5.37228132])

In [30]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])