In [1]:
import numpy as np

In [2]:
myarr = np.array([['nawsshad', 'sami', 'joy'], ['robin', 'sami', 'bob']], dtype=np.dtype('<U8'))

In [3]:
print(myarr[0, 1])

sami


In [4]:
myarr.shape

(2, 3)

In [5]:
myarr.size

6

In [6]:
myarr[0, 1] = 5654

In [7]:
myarr[0, 0].dtype

dtype('<U8')

In [8]:
myarr

array([['nawsshad', '5654', 'joy'],
       ['robin', 'sami', 'bob']], dtype='<U8')

# conversion from other python structures 

In [9]:
listarray = np.array([[1,2, 3], [4, 5, 6], [7, 8, 9], [2, 4, 6]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 4, 6]])

In [11]:
listarray.shape

(4, 3)

In [12]:
listarray.size

12

In [13]:
listarray.dtype 

dtype('int32')

In [14]:
np.array({1, 2, 3, 3, 4}) #not efficient in calculating for objects

array({1, 2, 3, 4}, dtype=object)

In [15]:
zeros_array = np.zeros((2, 7))

In [16]:
zeros_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
zeros_array.dtype

dtype('float64')

In [18]:
zeros_array.shape

(2, 7)

In [19]:
zeros_array.size

14

In [20]:
rng = np.arange(20)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
lspace = np.linspace(1, 21, 5)  #linear space

In [23]:
lspace

array([ 1.,  6., 11., 16., 21.])

In [24]:
metrix = np.identity(10)

In [25]:
metrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
metrix.shape

(10, 10)

In [27]:
metrix.size

100

In [28]:
metrix[9,9] = 65 #updating one of the item

In [29]:
metrix

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 65.]])

In [30]:
new_arr = np.arange(20)

In [31]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
new_arr.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [33]:
new_arr.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [34]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
new_arr = new_arr.reshape(4, 5)

In [36]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
new_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
check_arr = np.array([[2, 3, 4, 3, 1], [5, 56, 1, 7, 3]])

In [39]:
check_arr.ravel()

array([ 2,  3,  4,  3,  1,  5, 56,  1,  7,  3])

In [40]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [41]:
arr = np.array(x)

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
arr.sum(axis=0)

array([12,  8,  9])

In [44]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [45]:
lst = [1, 2, 3, 4]
lst*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [46]:
np_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)

In [47]:
np.sqrt(np_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
# np.array(np_arr, dtype=int)

In [49]:
np.log2(np_arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [50]:
np.exp(np_arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [51]:
np_arr.dtype

dtype('int32')

In [52]:
np.tan(np_arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [53]:
np.tanh(np_arr)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ,
       0.99998771, 0.99999834, 0.99999977, 0.99999997])